
pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'python-classes'
  dockerRepo: 'python-classes'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: docker-azure-pipelines
    repository: $(dockerRepo)
    command: push