
pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'python-classes'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile