version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-arrays-module:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip3 install -r packages.json
          name: installs the required py3 packages
      - run:
          command: cd tests && python3 test_arrays.py
          name: test the arrays module
      - run:
          command: cd tests && python3 test_hello.py
          name: test the hello module
      - run:
          command: cd tests && python3 test_histogram.py
          name: test the histogram module
      # - store_artifacts:
      #     path: out/
      #     destination: debian-build-py3_tarball.tar.gz
  docker-job:
    docker:
      - image: circleci/buildpack-deps:latest # the primary container, where your job's commands are run
    steps:
      - setup_remote_docker # use this command fur building and running docker commands into the circle ci container
      - checkout # check out the code in the project directory
      - run: docker build -t python-app . # run the `echo` command
      - run: docker run -it --rm --name my-py-app python-app 
      - run: mkdir test && ls
      - run: uname -a 


workflows:
  main:
    jobs:
      - test-arrays-module
      - docker-job
