version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-arrays-module:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip3 install -r packages.json
          name: installs the required py3 packages
      - run:
          command: chmod 775 app.sh && ./app.sh
          name: Test the python modules HIST | VIOLIN | ARRAY
      - run:
          command: tar -zcvf plot-bundle.tar.gz out && cp plot-bundle.gz /tmp
          name: Create the output bundle
      - store_artifacts:
          path: /tmp/plot-bundle.gz
          destination: plot-bundle.tar.gz

  docker-job-0:
    docker:
      - image: circleci/buildpack-deps:latest # the primary container, where your job's commands are run
    steps:
      - setup_remote_docker # use this command fur building and running docker commands into the circle ci container
      - checkout # check out the code in the project directory
      - run: docker build -t python-app . # run the `echo` command
      - run: docker run -it --rm --name my-py-app python-app >> docker_build.log
      - store_artifacts:
          path: docker_build.log
          destination: docker_build.log

  docker-job-1:
    docker:
      - image: circleci/buildpack-deps:latest # the primary container, where your job's commands are run
    steps:
      - setup_remote_docker # use this command fur building and running docker commands into the circle ci container
      - checkout # check out the code in the project directory
      - run: docker build -t python-app . # run the `echo` command
      - run: docker run -it --rm --name my-py-app python-app 


workflows:
  main:
    jobs:
      - test-arrays-module
      - docker-job-0
      - docker-job-1
